package com.example.civ6app;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;

public class WonderListActivity extends AppCompatActivity {

    WondersDataSource dataSource;
    ArrayAdapter<Wonder> wdrAdapter;
    ListView wonderList;
    TextView tvSelect;
    WonderArrayList wdrArrayList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_wonder_list);
        dataSource = new WondersDataSource(this);
        dataSource.open();
        wdrArrayList = new WonderArrayList(dataSource);
        insertAllWonders();

        wonderList = findViewById(R.id.wonderListView);
        tvSelect = (TextView) findViewById(R.id.textViewSelect);

        wdrAdapter = new WonderAdapter(this, R.layout.activity_wonder_list_details, R.id.textViewWonderName, wdrArrayList);
        wdrAdapter.setDropDownViewResource(R.layout.activity_wonder_list_details);
        wonderList.setAdapter(wdrAdapter);
        Log.d("out", "insert" + wdrArrayList.wonderArrayList.size());
        dataSource.close();
    }

    public void insertAllWonders() {

        wdrArrayList.setWonderArrayList();
        if (wdrArrayList.wonderArrayList.size() == 0) {
            dataSource.insertWonder("Alhambra", "Medieval", "+2 Great Work slots, +2  Envoys when you build a wonder, including Apadana, in this city", "Must be built on Hills adjacent to an Encampment District", "Castles", "710 production", "The Alhambra began as a small fortress, constructed in 889 AD by the Moors of Granada in Andalusia (Spain); then it was rebuilt and expanded by the emir Mohammed ben Al-Ahmar in the 11th Century and yet again expanded and converted into a royal palace by Sultan Yusuf I in 1333. The al-Hamra (literally, “the red one”), so named for its red clay fortress walls, was lavish – at least by European standards of the time – with all the comforts, including indoor plumbing. It integrated the natural beauty of the spot with structures and gardens designed and outfitted by the finest Muslim, Jewish, and even Christian craftsmen and artisans of the region. Among its most striking aspects, many of the interior walls and columns are inscribed in carved flowing Arabic script with poetry and verses from the Quran. The last sultan of the Nasrid dynasty, Muhammad XII, surrendered Granada to the Spanish in 1492 AD, without the Alhambra being attacked by the crusaders – otherwise it would be just another pile of rubble and memories of elegance.");
            dataSource.insertWonder("Amundsen-Scott Research Station", "Atomic", "+5 Great Scientist points per turn, +20% Science  and +10% Production in all cities. Yields are doubled if there are 5 Snow or Snow Hill tiles within 3 tiles of a city owned by this player.", "Must be built on a Snow or a Snow Hills tile next to Campus with a Research Lab.", "Rapid Development", "1620 production", "Scientists studying the South Pole brave its extreme conditions at the Amundsen-Scott Research Station. The station bears the names of Antarctic explorers Captain Robert Scott (the explorer who discovered the plateau where the South Pole is located) and Roald Amundsen (the first man to reach the South Pole—beating Scott’s expedition by 34 days). The original station, completed by the United States in 1957, became party to the Antarctic Treaty in 1959. All scientists working at the research station swore to freely explore and share scientific endeavors. Good intentions aside, the South Pole is no easy place to settle. The United States abandoned the station by 1975, whereupon it was buried under 30 feet of snow, excavated in 2010, and subsequently demolished with explosives. The new and improved Amundsen-Scott South Pole Station (established in 1999) features an Atmospheric Research Observatory, a section for studying astrophysics, and most importantly, internet access.");
            dataSource.insertWonder("Angkor Wat", "Medieval", "+2 Faith, +1 Population in all current cities when built, +1 Housing in all cities.", "Must be built adjacent to an Aqueduct district.", "Medieval Faires", "710 production", "It has stood for nearly 1,000 years, a monument to a god and possibly the final resting place of the conqueror king who built it. And still, the temple at Angkor Wat endures, its central tower rising 213 feet above the surrounding jungle. Constructed by the Khmer King Suryavarman II in the Twelfth century in what is now northern Cambodia, it is one of the world's tallest religious monuments. A pilgrim to the city-temple of the Hindu God Vishnu would first cross a 650-foot wide and 14-feet deep moat surrounding the structure before entering a 'gopura,' a three-towered entrance leading to a raised walkway. Inside the temple complex proper, they would find four smaller towers surrounding one central 213-foot tower, evoking the sacred Mount Meru. Khmer Shaivist temples typically face east, but because Angkor Wat faces west, the final resting place for Suryavarman's remains would be a temple honoring Vishnu.");
            dataSource.insertWonder("Apadana", "Classical", "+2 Amenities from entertainment, +2 Great General points per turn, +1 Military Policy slot", "Must be built adjacent to a  Capital.", "Political Philosophy", "400 production", "Though an apadana was a specific style of ancient construction, the Apadana at Persepolis most typified the style. Dozens of columns supported a wooden roof, all built atop an elevated stone surface accessible by large staircases. The structure was open to the elements, though temporary “rooms” could be created by hanging cloth between columns. Darius the Great began construction of the Apadana at Persepolis, and Xerxes I completed it. The dynasty’s accomplishments were literally carved into the wall, whether text declarations or reliefs depicting the splendor and majesty of the Persian kings. Unfortunately for the Achaemenids, the Apadana was mostly destroyed by Alexander the Great’s forces during his Persian conquests. Some of its columns remain standing in the modern day.");
            dataSource.insertWonder("Big Ben", "Industrial", "+6 Gold, +3 Great Mechant points per turn, +1 Economic policy slot, Upon construction the treasury is increased by 50%","Must be built next to a River adjacent to a Commercial Hub district with a Bank.", "Economics", "1450 production", "The giant bell, Big Ben, is housed in the Elizabeth Tower – so named to celebrate the Diamond Jubilee of Queen Elizabeth II (being just the “Clock Tower” before that) – at the north end of the Palace of Westminster, where sits the Houses of Parliament. Being rather casual in language, most Brits and flocks of tourists tend to refer to the whole thing as “Big Ben.” The great 16-ton bell was cast in August 1856 at the foundry at Stockton-on-Tees and recast at the Whitechapel Bell Foundry in April 1858 after it cracked while being transported to London. The pendulum clockwork was designed by the Astronomer Royal and crafted by the clockmaker Edward Dent and his stepson Frederick; it was ready in 1854. So fine is the precision, that adding or removing a penny (English, of course) to the pendulum will change the speed by four-tenths of a second each day. But all had to await the completion of the clock tower itself, which wasn’t done until 1859. Despite being silenced during wartime and the occasional breakdown, Big Ben has chimed the hour ever since.");
            dataSource.insertWonder("Bolshoi Theatre", "Industrial", "+2 Great Writer points per turn, +2 Great Musician points per turn, +1 Great work of Writing slow, +1 Great work of Music slot, Awards 2 randomly chosen free civics when completed.", "Must be built on flat land adjacent to a Theater Square district.", "Opera and Ballet", "1240 production", "The Imperial Bolshoi Theatre of Moscow – bolshoi being the Russian for “grand” – is home for the Bolshoi Ballet and Bolshoi Opera companies, among the oldest and largest in the world (the ballet has some 200 dancers). The ballet company was founded in March 1776 by Prince Urusov and Michael Maddox, a British theater manager; after performing in private homes for some years, the company was profitable enough to acquire the Petrovka Theater and opened there for the first time in December 1780. Sadly, the Petrovka burned down in 1805, to be replaced by the New Arbat Theater, which burned down in 1812 during Napoleon’s occupation of the city. The current Bolshoi Theater was built between 1821 and 1824, and it managed not to burn down – although it was renovated in 1843, 1856, 1921, 2002 and 2011. The last renovation included restoring the theater’s acoustics to the original high quality (which had been mucked up by the Soviets) and restoring the original imperial décor (which had been ripped out by those same Soviets). Despite prices ranging up to 5000 rubles, ballet and opera performances continue to be sold out – mostly to tourists.");
            dataSource.insertWonder("Broadway", "Modern", "+3 Great Writer points per turn, +3 Great Musician points per turn, +1 Great work of Writing slow, +2 Great work of Music slot, +20% Culture in that city, Gain a free random Atomic Era civic boost.", "Must be built on flat land adjacent to a Theater Square district.", "Mass Media", "1620 production", "Broadway is a 15-mile long thoroughfare through the heart of Manhattan and the Bronx in New York City, lined with offices, shops and apartments … but no-one thinks of those. Instead, Broadway is best known for the middle section between 42nd and 53rd Streets dubbed the “Great White Way” – the Theater District. Commencing in the mid-1800s a number of theaters opened on Broadway. In 1880 AD a stretch between Madison and Union squares was illuminated with arc lamps, making it one of the first electrically lit streets in the United States (leave it to New Yorkers to light up theaters before homes, hospitals and schools). Spurred by growing American wealth and cultural aspirations, the theaters made it a mecca of popular entertainment. By 1900 some 20 theaters had opened along this stretch, and so bright were their electric billboards that it became the Great White Way. In 1925 at its peak popularity, there were 80 theaters along Broadway, specializing in lavish productions, primarily revues and musicals.");
            dataSource.insertWonder("Casa de Contratación", "Renaissance", "+3 Great Merchant points per turn, Gain 3 Governor promotions, All your cities on your non-home continent with a Governor gain +15% Production, +15% Faith, +15% Gold,", "Must be built adjacent to a Government Plaza.", "Cartography", "920 production", "When Spain joined the late 15th Century’s exploration race, Queen Isabella I of Castile and Ferdinand II of Aragón realized they needed a firmer grasp on colonial trade and expansion. Through their Casa de Contratación, a 'House of Trade' created to regulate trade and procurement, the Spanish crown controlled everything related to trade and sea travel down to the smallest details. Even their navigation and cartography school kept literal trade secrets in house. Fandom may earn an affiliate commission on sales made from links on this page.Seville was home to the first incarnation of the Casa de Contración, but the agency moved to Cádiz in 1717. Moving to a city near the southern tip of Spain streamlined the influx of ships, which had previously traveled up the highly trafficked Guadalquivir River. The Casa remained in Cádiz until its termination in 1790 due to the empire’s growing debts.");
            dataSource.insertWonder("Chichen Itza", "Medieval", "+2 Cultural and +1 Production to all Rainforest tiles for this city", "Must be built on Rainforest.", "Guilds", "710 production", "The Mayans decided to build their great city of stone in the Yucatan in the middle of a jungle instead of on some nice beach. Whatever the logic of selecting such a spot, Chichen Itza was a metropolis of homes, temples, palaces, courtyards and ballcourts of extraordinary artistry; some of the ornamented structures date back 1500 years. The ball games were a special time in the city, as the winning captain was beheaded at the end of the play as a sacrifice to the gods (seems like a perfect reason to “throw” the game), possibly at the massive stepped-pyramid Temple of Kukulcan. Chichen Itza was a thriving concern until the 13th Century, when revolt and civil war broke out among the Mayans, at which point the city went into a steep decline from which it never recovered. What war didn’t take care of among the populace, disease and famine did. The center of the city was largely abandoned and in ruins by the time of the Spanish conquest.");
            dataSource.insertWonder("Colosseum", "Classical", "+2 Culture +2 Loyalty and +2 Amenities from entertainment, Culture and Loyalty bonus and Amenities are extended to each City Center within 6 Tiles.", "Must be built on flat land adjacent to an Entertainment Complex district with an Arena.", "Games and Recreation", "400 production", "The Flavian Amphitheater, better known as the “Coliseum” lies in the center of Rome. Construction began during the reign of Emperor Vespasian, c. 72 AD, funded by the spoils from the Jewish Second Temple after the fall of Jerusalem during the First Jewish-Roman War. Built of concrete and stone, it is the largest amphitheater ever built, and one of the great wonders of ancient architecture and engineering. It could hold between 50 and 80 thousand spectators to watch gladiatorial matches, animal hunts, mass executions, and more. By the time medieval Christianity had taken root, it had been repurposed to house low-rent apartments, workshops, quarters for a religious order, a quarry and a Christian shrine. Although knocked about by earthquakes and pillaged by stone-robbers, the Coliseum is still pretty impressive two millennia after the inaugural gladiatorial slaughter.");
            dataSource.insertWonder("Colossus", "Classical", "+3 Gold, +1 Great Admiral point per turn, +1 Trade Route capacity, Grants a Trader unit", "Must be built on Coast and adjacent to a Harbor district.", "Shipbuilding", "400 production", "Built from the smelted-down brass and iron of abandoned arms and equipment of a failed invasion, the Colossus of Rhodes was a 98-foot depiction of the Titan Helios erected to celebrate the victory. Construction under the direction of Chares of Lindos began in 292 BC, and by 280 was completed, to the amazement of all. Although the details are a bit hazy – the ancient histories being what they are – the towering statue overlooked the Mandraki harbor entrance set upon a 49-foot high marble pedestal. But it only stood for 56 years before being toppled by an earthquake. Ptolemy III of Egypt offered to pay for its reconstruction, but the Rhodians refused because the Delphi Oracle informed them that the gods were offended by it. Though the gods may have been offended, for nearly 900 years the rusting ruins of the statue were a tourist “must-see.” In 653 AD the forces of the Muslim caliph Muawiyah I overran Rhodes, and the new owners promptly sold it for scrap to Jewish merchants, who used – it is said – 900 camels to haul the mass away. From scrap to scrap.");
            dataSource.insertWonder("Cristo Redentor", "Modern", "+4 Culture, Tourism output and Relics and Holy Cities is not diminished by other civilizations who have researched The Enlightenment civic. Doubles Tourism output of Seaside Resorts across you civilization","Must be built on Hills.", "Mass Media", "1620 production", "The largest art deco statue in the world, Cristo Redentor (“Christ the Redeemer”) stands atop Corcovado Mountain 2300 feet above Rio de Janeiro, keeping a watchful eye on the sinners of that city. With arms spread wide to embrace the city sprawling below in spectacular disorder, this statue of Christ stands 98 feet tall, with the arms measuring 92 feet from fingertip to fingertip. It was sculpted by the Frenchman Paul Landowski, and built of reinforced concrete and soapstone. The idea of putting a giant statue of Christ above the city was first proposed by the Catholic priest Pedro Boss; proposed again in 1920 by the “Catholic Circle” of Rio, the group raised the necessary funds from donations, mostly from devout Brazilian Catholics (of course). Construction began in 1922, and the monument opened to the public in October 1931.");
            dataSource.insertWonder("Eiffel Tower", "Modern", "All tiles in your civilization gain +2 Appeal","Must be built on flat land adjacent to City Center.", "Steel", "1620 production", "Named after Alexandre Gustave Eiffel, whose company built the gigantic steel tower to serve as the main entrance for the 1889 Exposition Universelle (world’s fair) in Paris, the Eiffel Tower has come to symbolize the “City of Lights.” (And as garishly illuminated as the tower is at night, this seems fitting.) It was the tallest structure in the world at the time it opened to awestruck crowds, but it was also the subject of considerable controversy and criticism from self-appointed arbitrators of culture. Before it was even built a 300-member committee made up of some of the most prominent French engineers and artists dispatched a petition to the Minister of Works that opened: “We, writers, painters, sculptors, architects and passionate devotees of the hitherto untouched beauty of Paris, protest with all our strength, with all our indignation in the name of slighted French taste, against the erection … of this useless and monstrous Eiffel Tower.” Many were also upset that it was going to cost French taxpayers a million dollars – a not inconsiderable sum at the time. Luckily for the Parisian Tourism Board, the protests were ignored and up the Eiffel Tower went.");
            dataSource.insertWonder("Estádio do Maracanã", "Atomic", "+6 Culture in each city of you civilization, +2 Amenities  in each city of your civilization","Must be built on flat land adjacent to an Entertainment Complex with a Stadium.", "Professional Sports", "1740 production", "Officially the Estadio Jornalista Mario Filho – must have been a heck of a sports writer to get a stadium named after him – but better known as the Maracanã, the futebol stadium is part of a large complex in the heart of Rio de Janeiro. Begun in 1948 AD, after Brazil had won the right to host the FIFA World Cup, it was opened (more-or-less, for construction was not complete) for the first matches in that contest in 1950. Unfortunately, heavily favored Brazil was upset in the final by the team from Uruguay, 2-1, before a crowd of 199,854 rabid fans – making it the world’s largest (and loudest) stadium at the time. Since then the Maracanã has served as host to the Pan-American Games, another World Cup, numerous concerts and cultural events, and thousands of soccer matches. Having been renovated to a smaller capacity (78,838) and more comfortable accommodations (including 292 new toilets), the stadium hosted the Olympics (Summer, obviously) for the first time in 2016.");
            dataSource.insertWonder("Forbidden City", "Renaissance", "+5 Culture, +1 Wildcard policy slot.","Must be built on flat land adjacent to City Center.", "Printing", "920 production", "Lying in the center of Beijing, a visit to Gu Gong (the Imperial Palace of China) was forbidden to the common folk without special dispensation from the emperor himself; hence the complex became known across the land as the “Forbidden City” (much like most presidential residences these days). Construction of the walled “city” – liberally sprinkled with ornamental gardens, graceful terraces, restful fountains and lots of utilitarian administrative offices – began in 1408 AD under the guidance of the Yonglu Emperor, third of the Ming dynasty. The complex grew over the centuries, serving as home to 24 emperors of the Ming and Qing. It grew until it encompassed 9,999 rooms spread over 178 square acres, surrounded by a 170-foot wide moat and 32-foot high walls (just to make sure none of those commoners entered unchecked). At its peak, the Forbidden City was home to ten thousand people, all to serve the needs of one emperor. Now only a few hundred inhabit the sumptuous grounds, to serve as guides and janitors");
            dataSource.insertWonder("Golden Gate Bridge", "Modern", "+3 Amenities from entertainment, +4 Appeal to all tiles in this city, +100% Tourism from improvements and National Parks in this city, Acts as a Modern Road and creats Modern Roads in land tiles on either end if not present, Land units can cross without needing to disembark.","Must be built on a Coast tile. The bridge must run straight across the hex between two land tiles directly opposite one another. At least one water tile must be present on both the left and right sides of the bridge.", "Combustion", "1620 production", "Nestled in the San Francisco fog is the iconic Golden Gate Bridge, a 1.7 mile long suspension bridge that defied everything believed to be true about engineering when it was completed in 1937. Spanning across the Golden Gate Strait, this wonder of the modern world connects San Francisco to northern California counties, providing a necessary commuter route and unnecessary traffic for residents and visitors alike. Though its name suggests the color of its beams, the bridge is actually painted International Orange. Although this wasn't the original intended color for the project – black and yellow stripes were the leading choice – it complemented the landscape and gave the bridge some much needed visibility in the fog. So much visibility that it is believed to be the most photographed bridge in the world, and has made its mark on pop culture in movies, television, and video games.");
            dataSource.insertWonder("Great Bath", "Ancient", "+3 Housing, +1 Amenity from entertainment, The Floodplains tiles along the river containing the Wonder become immune to Flood damage at the cost of reducing Food and Production bonuses from flooding by 50%, +100%, Floodplains tiles belonging to this city gain +1 Faith for each time Flood damage is mitigated.","Must be built on a Floodplains tile.", "Pottery", "180 production", "The Great Bath at Mohenjo-daro was uncovered in 1926 in Sindh, Pakistan among the ruins of the Indus civilization. Though much of the life and culture of these people remains a mystery to scholars today, their ability to create this vast, water-tight structure was an impressive feat indeed. Measuring 12 by 7 meters with a depth of up to 2.4 meters, the tank was made of tightly packed bricks and mud, and sealed with a natural tar. But what was the purpose of a great public bath in a city where nearly every home contained its own bathing area? Though speculative, scholars seem to have agreed that it may have been used for religious purposes, as this was the closest structure to a temple uncovered in the area Today, the archaeological site lies far from the usual tourist routes in Pakistan, but many still visit the rural location to gaze in wonder at what remains of this ancient, mysterious city.");
            dataSource.insertWonder("Great Library", "Classical", "+2 Science, +1 Great Scientist point per turn, +2 Great Works of Writing slots, Receives boosts to all Ancient and Classical era technologies, , The Floodplains tiles along the river containing the Wonder become immune to Flood damage at the cost of reducing Food and Production bonuses from flooding by 50%, +100%, Floodplains tiles belonging to this city gain +1 Faith for each time Flood damage is mitigated.","Must be built on a Floodplains tile.", "Pottery", "180 production", "The Great Bath at Mohenjo-daro was uncovered in 1926 in Sindh, Pakistan among the ruins of the Indus civilization. Though much of the life and culture of these people remains a mystery to scholars today, their ability to create this vast, water-tight structure was an impressive feat indeed. Measuring 12 by 7 meters with a depth of up to 2.4 meters, the tank was made of tightly packed bricks and mud, and sealed with a natural tar. But what was the purpose of a great public bath in a city where nearly every home contained its own bathing area? Though speculative, scholars seem to have agreed that it may have been used for religious purposes, as this was the closest structure to a temple uncovered in the area Today, the archaeological site lies far from the usual tourist routes in Pakistan, but many still visit the rural location to gaze in wonder at what remains of this ancient, mysterious city.");




            wdrArrayList.setWonderArrayList();
        }

    }

}
