package com.example.civ6app;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

public class WonderListActivity extends AppCompatActivity {

    WondersDataSource dataSource;
    ArrayAdapter<Wonder> wdrAdapter;
    ListView wonderList;
    TextView tvSelect;
    WonderArrayList wdrArrayList;

    public static final String selectedName = "selectedWonder";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_wonder_list);
        dataSource = new WondersDataSource(this);
        dataSource.open();
        wdrArrayList = new WonderArrayList(dataSource);
        insertAllWonders();
        String condition;
        if (savedInstanceState == null) {
            Bundle extras = getIntent().getExtras();
            if(extras == null) {
                condition= null;
            } else {
                condition= extras.getString("condition");
            }
        } else {
            condition= (String) savedInstanceState.getSerializable("condition");
        }

        wdrArrayList.setWinCondition(condition);

        wonderList = findViewById(R.id.wonderListView);
        tvSelect = (TextView) findViewById(R.id.textViewSelect);

        wdrAdapter = new WonderAdapter(this, R.layout.activity_wonder_list_details, R.id.textViewWonderName, wdrArrayList);
        wdrAdapter.setDropDownViewResource(R.layout.activity_wonder_list_details);
        wonderList.setAdapter(wdrAdapter);

        wonderList.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> parent, final View view, int position, long id) {
                Wonder wdr = (Wonder) parent.getItemAtPosition(position);
                Intent detailActIntent = new Intent(parent.getContext(), activity_wonder_list_details_full.class);
                detailActIntent.putExtra(selectedName, wdr.toString());
                startActivity(detailActIntent);
            }
        });


        dataSource.close();
    }

    public void insertAllWonders() {

        wdrArrayList.setWonderArrayList();
        if (wdrArrayList.wonderArrayList.size() == 0) {
            dataSource.insertWonder("Alhambra", "Medieval", "+2 Great Work slots, +2  Envoys when you build a wonder, including Apadana, in this city", "Must be built on Hills adjacent to an Encampment District", "Castles", "710 production", "The Alhambra began as a small fortress, constructed in 889 AD by the Moors of Granada in Andalusia (Spain); then it was rebuilt and expanded by the emir Mohammed ben Al-Ahmar in the 11th Century and yet again expanded and converted into a royal palace by Sultan Yusuf I in 1333. The al-Hamra (literally, “the red one”), so named for its red clay fortress walls, was lavish – at least by European standards of the time – with all the comforts, including indoor plumbing. It integrated the natural beauty of the spot with structures and gardens designed and outfitted by the finest Muslim, Jewish, and even Christian craftsmen and artisans of the region. Among its most striking aspects, many of the interior walls and columns are inscribed in carved flowing Arabic script with poetry and verses from the Quran. The last sultan of the Nasrid dynasty, Muhammad XII, surrendered Granada to the Spanish in 1492 AD, without the Alhambra being attacked by the crusaders – otherwise it would be just another pile of rubble and memories of elegance.");
            dataSource.insertWonder("Amundsen-Scott Research Station", "Atomic", "+5 Great Scientist points per turn, +20% Science  and +10% Production in all cities. Yields are doubled if there are 5 Snow or Snow Hill tiles within 3 tiles of a city owned by this player.", "Must be built on a Snow or a Snow Hills tile next to Campus with a Research Lab.", "Rapid Development", "1620 production", "Scientists studying the South Pole brave its extreme conditions at the Amundsen-Scott Research Station. The station bears the names of Antarctic explorers Captain Robert Scott (the explorer who discovered the plateau where the South Pole is located) and Roald Amundsen (the first man to reach the South Pole—beating Scott’s expedition by 34 days). The original station, completed by the United States in 1957, became party to the Antarctic Treaty in 1959. All scientists working at the research station swore to freely explore and share scientific endeavors. Good intentions aside, the South Pole is no easy place to settle. The United States abandoned the station by 1975, whereupon it was buried under 30 feet of snow, excavated in 2010, and subsequently demolished with explosives. The new and improved Amundsen-Scott South Pole Station (established in 1999) features an Atmospheric Research Observatory, a section for studying astrophysics, and most importantly, internet access.");
            dataSource.insertWonder("Angkor Wat", "Medieval", "+2 Faith, +1 Population in all current cities when built, +1 Housing in all cities.", "Must be built adjacent to an Aqueduct district.", "Medieval Faires", "710 production", "It has stood for nearly 1,000 years, a monument to a god and possibly the final resting place of the conqueror king who built it. And still, the temple at Angkor Wat endures, its central tower rising 213 feet above the surrounding jungle. Constructed by the Khmer King Suryavarman II in the Twelfth century in what is now northern Cambodia, it is one of the world's tallest religious monuments. A pilgrim to the city-temple of the Hindu God Vishnu would first cross a 650-foot wide and 14-feet deep moat surrounding the structure before entering a 'gopura,' a three-towered entrance leading to a raised walkway. Inside the temple complex proper, they would find four smaller towers surrounding one central 213-foot tower, evoking the sacred Mount Meru. Khmer Shaivist temples typically face east, but because Angkor Wat faces west, the final resting place for Suryavarman's remains would be a temple honoring Vishnu.");
            dataSource.insertWonder("Apadana", "Classical", "+2 Amenities from entertainment, +2 Great General points per turn, +1 Military Policy slot", "Must be built adjacent to a  Capital.", "Political Philosophy", "400 production", "Though an apadana was a specific style of ancient construction, the Apadana at Persepolis most typified the style. Dozens of columns supported a wooden roof, all built atop an elevated stone surface accessible by large staircases. The structure was open to the elements, though temporary “rooms” could be created by hanging cloth between columns. Darius the Great began construction of the Apadana at Persepolis, and Xerxes I completed it. The dynasty’s accomplishments were literally carved into the wall, whether text declarations or reliefs depicting the splendor and majesty of the Persian kings. Unfortunately for the Achaemenids, the Apadana was mostly destroyed by Alexander the Great’s forces during his Persian conquests. Some of its columns remain standing in the modern day.");
            dataSource.insertWonder("Big Ben", "Industrial", "+6 Gold, +3 Great Mechant points per turn, +1 Economic policy slot, Upon construction the treasury is increased by 50%","Must be built next to a River adjacent to a Commercial Hub district with a Bank.", "Economics", "1450 production", "The giant bell, Big Ben, is housed in the Elizabeth Tower – so named to celebrate the Diamond Jubilee of Queen Elizabeth II (being just the “Clock Tower” before that) – at the north end of the Palace of Westminster, where sits the Houses of Parliament. Being rather casual in language, most Brits and flocks of tourists tend to refer to the whole thing as “Big Ben.” The great 16-ton bell was cast in August 1856 at the foundry at Stockton-on-Tees and recast at the Whitechapel Bell Foundry in April 1858 after it cracked while being transported to London. The pendulum clockwork was designed by the Astronomer Royal and crafted by the clockmaker Edward Dent and his stepson Frederick; it was ready in 1854. So fine is the precision, that adding or removing a penny (English, of course) to the pendulum will change the speed by four-tenths of a second each day. But all had to await the completion of the clock tower itself, which wasn’t done until 1859. Despite being silenced during wartime and the occasional breakdown, Big Ben has chimed the hour ever since.");
            dataSource.insertWonder("Bolshoi Theatre", "Industrial", "+2 Great Writer points per turn, +2 Great Musician points per turn, +1 Great work of Writing slow, +1 Great work of Music slot, Awards 2 randomly chosen free civics when completed.", "Must be built on flat land adjacent to a Theater Square district.", "Opera and Ballet", "1240 production", "The Imperial Bolshoi Theatre of Moscow – bolshoi being the Russian for “grand” – is home for the Bolshoi Ballet and Bolshoi Opera companies, among the oldest and largest in the world (the ballet has some 200 dancers). The ballet company was founded in March 1776 by Prince Urusov and Michael Maddox, a British theater manager; after performing in private homes for some years, the company was profitable enough to acquire the Petrovka Theater and opened there for the first time in December 1780. Sadly, the Petrovka burned down in 1805, to be replaced by the New Arbat Theater, which burned down in 1812 during Napoleon’s occupation of the city. The current Bolshoi Theater was built between 1821 and 1824, and it managed not to burn down – although it was renovated in 1843, 1856, 1921, 2002 and 2011. The last renovation included restoring the theater’s acoustics to the original high quality (which had been mucked up by the Soviets) and restoring the original imperial décor (which had been ripped out by those same Soviets). Despite prices ranging up to 5000 rubles, ballet and opera performances continue to be sold out – mostly to tourists.");
            dataSource.insertWonder("Broadway", "Modern", "+3 Great Writer points per turn, +3 Great Musician points per turn, +1 Great work of Writing slow, +2 Great work of Music slot, +20% Culture in that city, Gain a free random Atomic Era civic boost.", "Must be built on flat land adjacent to a Theater Square district.", "Mass Media", "1620 production", "Broadway is a 15-mile long thoroughfare through the heart of Manhattan and the Bronx in New York City, lined with offices, shops and apartments … but no-one thinks of those. Instead, Broadway is best known for the middle section between 42nd and 53rd Streets dubbed the “Great White Way” – the Theater District. Commencing in the mid-1800s a number of theaters opened on Broadway. In 1880 AD a stretch between Madison and Union squares was illuminated with arc lamps, making it one of the first electrically lit streets in the United States (leave it to New Yorkers to light up theaters before homes, hospitals and schools). Spurred by growing American wealth and cultural aspirations, the theaters made it a mecca of popular entertainment. By 1900 some 20 theaters had opened along this stretch, and so bright were their electric billboards that it became the Great White Way. In 1925 at its peak popularity, there were 80 theaters along Broadway, specializing in lavish productions, primarily revues and musicals.");
            dataSource.insertWonder("Casa de Contratación", "Renaissance", "+3 Great Merchant points per turn, Gain 3 Governor promotions, All your cities on your non-home continent with a Governor gain +15% Production, +15% Faith, +15% Gold,", "Must be built adjacent to a Government Plaza.", "Cartography", "920 production", "When Spain joined the late 15th Century’s exploration race, Queen Isabella I of Castile and Ferdinand II of Aragón realized they needed a firmer grasp on colonial trade and expansion. Through their Casa de Contratación, a 'House of Trade' created to regulate trade and procurement, the Spanish crown controlled everything related to trade and sea travel down to the smallest details. Even their navigation and cartography school kept literal trade secrets in house. Fandom may earn an affiliate commission on sales made from links on this page.Seville was home to the first incarnation of the Casa de Contración, but the agency moved to Cádiz in 1717. Moving to a city near the southern tip of Spain streamlined the influx of ships, which had previously traveled up the highly trafficked Guadalquivir River. The Casa remained in Cádiz until its termination in 1790 due to the empire’s growing debts.");
            dataSource.insertWonder("Chichen Itza", "Medieval", "+2 Cultural and +1 Production to all Rainforest tiles for this city", "Must be built on Rainforest.", "Guilds", "710 production", "The Mayans decided to build their great city of stone in the Yucatan in the middle of a jungle instead of on some nice beach. Whatever the logic of selecting such a spot, Chichen Itza was a metropolis of homes, temples, palaces, courtyards and ballcourts of extraordinary artistry; some of the ornamented structures date back 1500 years. The ball games were a special time in the city, as the winning captain was beheaded at the end of the play as a sacrifice to the gods (seems like a perfect reason to “throw” the game), possibly at the massive stepped-pyramid Temple of Kukulcan. Chichen Itza was a thriving concern until the 13th Century, when revolt and civil war broke out among the Mayans, at which point the city went into a steep decline from which it never recovered. What war didn’t take care of among the populace, disease and famine did. The center of the city was largely abandoned and in ruins by the time of the Spanish conquest.");
            dataSource.insertWonder("Colosseum", "Classical", "+2 Culture +2 Loyalty and +2 Amenities from entertainment, Culture and Loyalty bonus and Amenities are extended to each City Center within 6 Tiles.", "Must be built on flat land adjacent to an Entertainment Complex district with an Arena.", "Games and Recreation", "400 production", "The Flavian Amphitheater, better known as the “Coliseum” lies in the center of Rome. Construction began during the reign of Emperor Vespasian, c. 72 AD, funded by the spoils from the Jewish Second Temple after the fall of Jerusalem during the First Jewish-Roman War. Built of concrete and stone, it is the largest amphitheater ever built, and one of the great wonders of ancient architecture and engineering. It could hold between 50 and 80 thousand spectators to watch gladiatorial matches, animal hunts, mass executions, and more. By the time medieval Christianity had taken root, it had been repurposed to house low-rent apartments, workshops, quarters for a religious order, a quarry and a Christian shrine. Although knocked about by earthquakes and pillaged by stone-robbers, the Coliseum is still pretty impressive two millennia after the inaugural gladiatorial slaughter.");
            dataSource.insertWonder("Colossus", "Classical", "+3 Gold, +1 Great Admiral point per turn, +1 Trade Route capacity, Grants a Trader unit", "Must be built on Coast and adjacent to a Harbor district.", "Shipbuilding", "400 production", "Built from the smelted-down brass and iron of abandoned arms and equipment of a failed invasion, the Colossus of Rhodes was a 98-foot depiction of the Titan Helios erected to celebrate the victory. Construction under the direction of Chares of Lindos began in 292 BC, and by 280 was completed, to the amazement of all. Although the details are a bit hazy – the ancient histories being what they are – the towering statue overlooked the Mandraki harbor entrance set upon a 49-foot high marble pedestal. But it only stood for 56 years before being toppled by an earthquake. Ptolemy III of Egypt offered to pay for its reconstruction, but the Rhodians refused because the Delphi Oracle informed them that the gods were offended by it. Though the gods may have been offended, for nearly 900 years the rusting ruins of the statue were a tourist “must-see.” In 653 AD the forces of the Muslim caliph Muawiyah I overran Rhodes, and the new owners promptly sold it for scrap to Jewish merchants, who used – it is said – 900 camels to haul the mass away. From scrap to scrap.");
            dataSource.insertWonder("Cristo Redentor", "Modern", "+4 Culture, Tourism output and Relics and Holy Cities is not diminished by other civilizations who have researched The Enlightenment civic. Doubles Tourism output of Seaside Resorts across you civilization","Must be built on Hills.", "Mass Media", "1620 production", "The largest art deco statue in the world, Cristo Redentor (“Christ the Redeemer”) stands atop Corcovado Mountain 2300 feet above Rio de Janeiro, keeping a watchful eye on the sinners of that city. With arms spread wide to embrace the city sprawling below in spectacular disorder, this statue of Christ stands 98 feet tall, with the arms measuring 92 feet from fingertip to fingertip. It was sculpted by the Frenchman Paul Landowski, and built of reinforced concrete and soapstone. The idea of putting a giant statue of Christ above the city was first proposed by the Catholic priest Pedro Boss; proposed again in 1920 by the “Catholic Circle” of Rio, the group raised the necessary funds from donations, mostly from devout Brazilian Catholics (of course). Construction began in 1922, and the monument opened to the public in October 1931.");
            dataSource.insertWonder("Eiffel Tower", "Modern", "All tiles in your civilization gain +2 Appeal","Must be built on flat land adjacent to City Center.", "Steel", "1620 production", "Named after Alexandre Gustave Eiffel, whose company built the gigantic steel tower to serve as the main entrance for the 1889 Exposition Universelle (world’s fair) in Paris, the Eiffel Tower has come to symbolize the “City of Lights.” (And as garishly illuminated as the tower is at night, this seems fitting.) It was the tallest structure in the world at the time it opened to awestruck crowds, but it was also the subject of considerable controversy and criticism from self-appointed arbitrators of culture. Before it was even built a 300-member committee made up of some of the most prominent French engineers and artists dispatched a petition to the Minister of Works that opened: “We, writers, painters, sculptors, architects and passionate devotees of the hitherto untouched beauty of Paris, protest with all our strength, with all our indignation in the name of slighted French taste, against the erection … of this useless and monstrous Eiffel Tower.” Many were also upset that it was going to cost French taxpayers a million dollars – a not inconsiderable sum at the time. Luckily for the Parisian Tourism Board, the protests were ignored and up the Eiffel Tower went.");
            dataSource.insertWonder("Estádio do Maracanã", "Atomic", "+6 Culture in each city of you civilization, +2 Amenities  in each city of your civilization","Must be built on flat land adjacent to an Entertainment Complex with a Stadium.", "Professional Sports", "1740 production", "Officially the Estadio Jornalista Mario Filho – must have been a heck of a sports writer to get a stadium named after him – but better known as the Maracanã, the futebol stadium is part of a large complex in the heart of Rio de Janeiro. Begun in 1948 AD, after Brazil had won the right to host the FIFA World Cup, it was opened (more-or-less, for construction was not complete) for the first matches in that contest in 1950. Unfortunately, heavily favored Brazil was upset in the final by the team from Uruguay, 2-1, before a crowd of 199,854 rabid fans – making it the world’s largest (and loudest) stadium at the time. Since then the Maracanã has served as host to the Pan-American Games, another World Cup, numerous concerts and cultural events, and thousands of soccer matches. Having been renovated to a smaller capacity (78,838) and more comfortable accommodations (including 292 new toilets), the stadium hosted the Olympics (Summer, obviously) for the first time in 2016.");
            dataSource.insertWonder("Forbidden City", "Renaissance", "+5 Culture, +1 Wildcard policy slot.","Must be built on flat land adjacent to City Center.", "Printing", "920 production", "Lying in the center of Beijing, a visit to Gu Gong (the Imperial Palace of China) was forbidden to the common folk without special dispensation from the emperor himself; hence the complex became known across the land as the “Forbidden City” (much like most presidential residences these days). Construction of the walled “city” – liberally sprinkled with ornamental gardens, graceful terraces, restful fountains and lots of utilitarian administrative offices – began in 1408 AD under the guidance of the Yonglu Emperor, third of the Ming dynasty. The complex grew over the centuries, serving as home to 24 emperors of the Ming and Qing. It grew until it encompassed 9,999 rooms spread over 178 square acres, surrounded by a 170-foot wide moat and 32-foot high walls (just to make sure none of those commoners entered unchecked). At its peak, the Forbidden City was home to ten thousand people, all to serve the needs of one emperor. Now only a few hundred inhabit the sumptuous grounds, to serve as guides and janitors");
            dataSource.insertWonder("Golden Gate Bridge", "Modern", "+3 Amenities from entertainment, +4 Appeal to all tiles in this city, +100% Tourism from improvements and National Parks in this city, Acts as a Modern Road and creats Modern Roads in land tiles on either end if not present, Land units can cross without needing to disembark.","Must be built on a Coast tile. The bridge must run straight across the hex between two land tiles directly opposite one another. At least one water tile must be present on both the left and right sides of the bridge.", "Combustion", "1620 production", "Nestled in the San Francisco fog is the iconic Golden Gate Bridge, a 1.7 mile long suspension bridge that defied everything believed to be true about engineering when it was completed in 1937. Spanning across the Golden Gate Strait, this wonder of the modern world connects San Francisco to northern California counties, providing a necessary commuter route and unnecessary traffic for residents and visitors alike. Though its name suggests the color of its beams, the bridge is actually painted International Orange. Although this wasn't the original intended color for the project – black and yellow stripes were the leading choice – it complemented the landscape and gave the bridge some much needed visibility in the fog. So much visibility that it is believed to be the most photographed bridge in the world, and has made its mark on pop culture in movies, television, and video games.");
            dataSource.insertWonder("Great Bath", "Ancient", "+3 Housing, +1 Amenity from entertainment, The Floodplains tiles along the river containing the Wonder become immune to Flood damage at the cost of reducing Food and Production bonuses from flooding by 50%, +100%, Floodplains tiles belonging to this city gain +1 Faith for each time Flood damage is mitigated.","Must be built on a Floodplains tile.", "Pottery", "180 production", "The Great Bath at Mohenjo-daro was uncovered in 1926 in Sindh, Pakistan among the ruins of the Indus civilization. Though much of the life and culture of these people remains a mystery to scholars today, their ability to create this vast, water-tight structure was an impressive feat indeed. Measuring 12 by 7 meters with a depth of up to 2.4 meters, the tank was made of tightly packed bricks and mud, and sealed with a natural tar. But what was the purpose of a great public bath in a city where nearly every home contained its own bathing area? Though speculative, scholars seem to have agreed that it may have been used for religious purposes, as this was the closest structure to a temple uncovered in the area Today, the archaeological site lies far from the usual tourist routes in Pakistan, but many still visit the rural location to gaze in wonder at what remains of this ancient, mysterious city.");
            dataSource.insertWonder("Great Library", "Classical", "+1 Great Writer point per turn,Receive a random tech boost after another player recruits a Great Scientist.","Must be built on flat land adjacent to a Campus with a Library.", "Recorded History", "400 production", "It is generally assumed that the Royal Library of Alexandria was founded at the beginning of the 3rd Century BC during the reign of Ptolemy II after his father had built the Temple of the Muses on the site. The original collection is attributed to Demetrius Phalereus, a student of Aristotle’s (supposedly the famed philosopher’s own scrolls served as the seed); with the patronage of Ptolemy’s successors, the holdings eventually reached between 400 and 700 thousand papyrus scrolls and various vellum codices. Expansion of the collection became an obsession for some of the rulers; by decree of Ptolemy III, all visitors to the city had to surrender any writings in their possession, which were copied for the Library. Sources differ widely on responsibility for the fiery destruction of the Great Library’s collection of texts; usual suspects listed include Julius Caesar’s troops in 48 BC, Roman Emperor Aurelian c. 270 AD, and others. But it does appear that the last vestiges were burned in 391 at the orders of the Patriarch Theophilus to eradicate pagan influences in Egypt – not the last time Christians would burn books.");
            dataSource.insertWonder("Great Lighthouse", "Classical", "+3 Gold, +1 Great Admiral point per turn, +1 Movement for all naval units.","Must be built on the Coast and adjacent to a Harbor district with a Lighthouse.", "Celestial Navigation", "290 production", "The Great Lighthouse of Alexandria (one of the seventeen cities the egotistical young general named after himself), known to the ancients as the Pharos, was reputed to stand between 393 and 450 feet high – making it one of the tallest structures in civilization for many centuries. Begun in 280 BC by Ptolemy Sotor, one of Alexander’s Macedonian generals and successors, on a small island to help guide trade ships into the harbor of the thriving city, the Lighthouse was not completed until 247 at the phenomenal cost of 800 talents. Its light at the top of the massive tower was produced by a furnace reputedly made of solid blocks of limestone, and was visible for one hundred miles. Although badly damaged by three earthquakes between 956 and 1323 AD, it did not topple over – making it the third-longest surviving of the ancient wonders. Finally, the sultan of Egypt quarried the remaining stone (some had fallen into the harbor) to build the Citadel of Qaitbay in 1480 to protect Alexandria against the Ottoman Turks (didn’t work).");
            dataSource.insertWonder("Great Zimbabwe", "Renaissance", "+5 Gold, +2 Great Merchant point per turn, +1 Trade route capacity. Your Trade Routes from this city get +2 Gold for every Bonus resource in this city's territory.","Must be built adjacent to Cattle and a Commercial Hub district with a Market.", "Banking", "920 production", "According to one set of legends, Great Zimbabwe was the palace complex of the Queen of Sheba. According to another set, it was where the laborers of King Solomon’s Mines – which were thought nearby by a generation of deluded treasure hunters – relaxed during their time off. In point of boring fact, it was the capital city, eventually covering some 1700 acres with a peak population of around 18 thousand, of the Kingdom of Zimbabwe which arose in 1220 AD and was gone by 1450 AD. Built entirely of stone (quite a feat in the jungle), Great Zimbabwe was soon afterward abandoned and fell into ruin. The earliest known record of the ruins is by the Portuguese officer Vicente Pegado, written in 1531. He makes mention of great walls, made of chiseled stone fitted without mortar. The ruins lie in three groupings: the Hill Complex, the Valley Complex, and the Great Enclosure, where the majority of the archaeological artifacts have been found: soapstone figurines, gold beads, copper ingots, bronze spearheads, jeweled pendants and bracelets, and much else. So, maybe those treasure hunters weren’t so deluded after all.");
            dataSource.insertWonder("Hagia Sophia", "Medieval", "+4 Faith, Missionaries and Apostles can spread religion 1 extra time.","Must be built on flat land adjacent to a Holy Site district, and player must have founded a religion.", "Buttress", "710 production", "The city of Istanbul (or Constantinople or Byzantium, as one prefers) has been home to many peoples, although best known in its role as capital for the Byzantine and then the Ottoman empires. And it has been home to many faiths, most notably Eastern Orthodox Christianity and Islam respectively. Nothing personifies that personality disorder under one dome so well as the fabulous Hagia Sophia (literally, “holy wisdom”). Built around 532 AD as the Greek Orthodox patriarchal basilica, it has served worshipers for almost 1500 years. In 1453 when Constantinople was captured by the Ottomans and renamed, the Hagia Sophia was converted to a mosque. Ornate and stately, the structure is built of stone and marble, topped by a golden dome measuring 102 feet in diameter, before the Muslim rulers added four minarets. The structure has survived several earthquakes, fires, riots, lootings (such as during the Fourth Crusade), and one massacre (when the elderly and infirm who had taken shelter there were slaughtered by the Ottoman conquerors). Today the Hagia Sophia serves as a museum, and yet remains one of the most striking buildings in civilization.");
            dataSource.insertWonder("Hanging Gardens", "Ancient", "Increases Growth by 15% in all cities. +2 Housing.", "Must be built next to a River.", "Irrigation", "180 production","The Hanging Gardens may not have even existed, much less been a “wonder”; no Babylonian source mentions them, and there is no archaeological evidence for them (unlike for other ancient wonders of the world). The primary evidence for the Gardens comes from several Greek and Roman texts – how they were created, why they were created, their size and variety, even how they were watered. According to these, Nebuchadnezzar II constructed the Gardens c. 600 BC for his (obviously spoiled) homesick Median wife Amytis, who missed the green hills of her birthplace. The “historical” sources also state that the Gardens were an ascending series of terraces (much like a ziggurat) built of mud bricks and containing all manner of plants. The base was supposedly 400 feet square, and the whole mass rose 75 feet into the very dry air; estimates are that the gardens would have required 8200 gallons of water a day to keep the plants alive in Babylon. If the Gardens did exist, it is assumed these were destroyed sometime during the first century AD.");
            dataSource.insertWonder("Hermitage", "Industrial", "+3 Great Artist points per turn, +4 Great works of Art slots", "Must be built next to a River on a non-Desert and non-Tundra tile.", "Natural History", "1450 production","The core of what is today the famed Hermitage in St. Petersburg encompasses the monumental Winter Palace, residence of the Tsars since 1764 AD when Catherine the Great completed the palace on a scale to reflect the might and power of Imperial Russia. Catherine declared it her “treasure,” and proceeded to fill it with treasures – Renaissance paintings, jeweled and gilded crafts (the likes of Fabergé eggs, for instance), the crown jewels, and other trinkets. After adding several extensions to the palace and some reorganizing, in 1852 Nicholas I opened it to the public. And the Tsars kept adding to the collection. With the February Revolution of 1917, the building briefly housed the Provisional Government, until the Bolsheviks seized power in October and declared it a gift to the proletariat. Now spread across five buildings, the Hermitage is one of the largest museums in the world, with over three million art and historical items in its collection, including the largest gathering of paintings in the world.");
            dataSource.insertWonder("Huey Toecalli", "Medieval", "+1 Amenitiy from Entertainment for each adjacent lake tile. +1 Food and +1 Production for each Lake tile in your empire.", "Must be built on a Lake tile adjacent to land.", "Military Tactics", "710 production","In the Aztec Empire, a teocalli was a terraced pyramid, surmounted by a temple on top, site of all the important religious rituals in the town. The greatest was located in the heart of Tenochtitlan, the Huey Teocalli (or, according to the Spanish, the Templo Mayor) dedicated to a pair of gods: Huitzilopochtli, the god of war, and Tlaloc, the god of agriculture (an indication of what was important in Aztec culture). Each god had a separate temple, reached by separate staircases. Mesoamerican pyramids tended to be rebuilt, using the prior structure as the base for the new, expanded version. Thus, Huey Teocalli was rebuilt six times after the first was completed around 1325 AD. The seventh, and last, was the one sacked and destroyed by Cortes and his conquistadors. Likely they took a dim view of the place, as it was given over to curious celebrations… such as the Panquetzaliztli festival celebrating Huitzilopochtli, when an effigy of the god made from amaranth seeds, bones, honey, and human blood was venerated, then given over to the populace to be eaten.");
            dataSource.insertWonder("Jebel Barkal", "Classical", "Awards 4 Iron per turn, Provides +4 Faith to your cities that are within 6 tiles.", "Must be built on a Desert Hills tile.", "Iron Working", "400 production","A lonely mountain rises from the flat Sudanese desert, west of a bend in the Nile. At its base once stood a palace where ancient kingdoms ruled for centuries. Now, there are only ruins. Fandom may earn an affiliate commission on sales made from links on this page. Easily recognizable from a great distance, the flat-topped mountain of Jebel Barkal was a waypoint for travelers in ancient times. It indicated a point of relatively safe crossing (just downstream of the Nile's Fourth Cataract). After the Fifteenth Century BCE, it also noted the location of Napata, Egypt's southernmost border city that, 500 years later, would become the capital of the Nubian Kingdom of Kush. Since the 19th Century, archaeologists have excavated a wealth of historical information from Jebel Barkal including temple ruins, stonework carved into the mountain, and ancient inscriptions dating back to the Egyptian occupation of the region. The Nubian pyramids in the shadow of the mountain later served as tombs for Meroitic kings and queens.");
            dataSource.insertWonder("Kilwa Kisiwani", "Medieval", "+3 Envoys when built, When you are the Suzerain of a City-state this city gains a +15% boost to the yield provided by that City-state, If you are the Suzerain of 2 or more City-states of that type an additional 15% boost is given to all your cities.", "Must be built on a flat tile adjacent to a Coast.", "Machinery", "710 production","The East African city-state Kilwa Kisiwani was once a major destination for trade in the Indian Ocean. Ivory, gold, and perfumes flowed through its markets. At its height, Kilwa Kisiwani contained some of the finest architecture in East Africa: the Great Mosque (which remained the world’s largest mosque until the 16th Century) and Husuni Kubwa (a classy palace), both of which survived to the modern day. Kilwa Kisiwani flourished as a major trade city until the Portuguese arrived in 1498 to “make improvements” to the city’s infrastructure (if extorting tribute can be considered an improvement). Over the centuries, a series of foreign conquerors wrestled control of the city from one another, until it was abandoned in 1840.");
            dataSource.insertWonder("Kotoku-in", "Medieval", "+20% Faith in this city, Grants 4 Warrior Monks.", "Must be built adjacent to a Holy Site with a Temple.", "Divine Right", "710 production","Serene, enduring, and somewhat mysterious, the Buddha statue known as the Daibutsu sits outside of Kamakura’s Kōtoku-in. Towering over the Buddhist temple’s visitors, the Daibutsu patiently greets both faithful and tourist alike. An unknown artist cast the Great Buddha of Kamakura out of bronze, which has since oxidized into a muted green color through natural weathering. Fandom may earn an affiliate commission on sales made from links on this page. However, the Kōtoku-in’s artist clearly built it to last. It survived an earthquake and two typhoons, one of which destroyed the building that used to surround it. The statue remains unfazed by nature’s attempts to unseat its 750-year meditation.");
            dataSource.insertWonder("Machu Picchu", "Classical", "+4 Gold, Mountain tiles provide a standard adjacency bonus to Commercial Hub, Theater Square and Industrial Zone districts in all cities.", "Must be built on a Mountain tile that does not contain a Volcano.", "Engineering", "400 production","At 2,430 meters above sea level in the Andes Mountains of Peru is the historic site of Machu Picchu. Once a royal estate, or perhaps a religious site, for the Incan empire, it was abandoned in the 16th century when the civilization was destroyed by a Spanish invasion. Lost to history for hundreds of years, Machu Picchu was rediscovered in 1911 by American archaeologist Hiram Bingham, exciting tourists immediately and for years to come. Today, hundreds of thousands of tourists visit the site annually. Most remarkable about the site is how seamlessly it blends into the natural world. This lost city is made up of stone terraces, a farming sector, homes, temples, and more – approximately 200 buildings in total. The finely fit stonework and intricate irrigation systems nod to the sophistication of the lost Incan civilization.");
            dataSource.insertWonder("Mahabodhi Temple", "Classical", "+4 Faith, Grants 2 Apostles, +2 Diplomatic Victory Points When built.", "Must be built on Woods adjacent to a Holy Site district with a Temple, and player must have founded a religion.", "Theology", "400 production","The Mahabodhi Temple (or “Great Awakening” Temple) in Bodh Gaya is one of the four sacred sites of the Lord Buddha’s (Siddhartha Gautama) life, and the very spot where he attained Enlightenment. On the western side of the temple is the sacred Bodhi Tree, the very fig tree under which the Buddha was sitting when he did so. Be all that as it may, the first Mahabodhi Temple (there have been a couple) was built by the Emperor Asoka c. 250 BC. The current temple complex – notably the great tower, one of the first brick structures in India – dates from the 5th and 6th centuries AD. A high wall around the temple grounds was added at a later, undocumented, date; the wall encompasses the Bodhi Tree and six other sacred site of Buddha’s very enlightenment, since he spent seven weeks in seven different spots meditating on his very own revelations, as well as numerous Votive stupas. In the 1880s the British Raj undertook a restoration effort; in 1949 control of the very site passed to the state government of Bihar. Today, Buddhists from the world over make pilgrimage to Bodh Gaya as the holiest place of their very faith.");
            dataSource.insertWonder("Mausoleum at Halicarnassus", "Classical", "+1 Science, Faith, and Culture on all Coast tiles in this city, All Great Engineers have an additional charge.", "Must be built on a coastal tile adjacent to a Harbor district.", "Defensive Tactics", "400 production","The Persian satrap Mausolus had a tomb built for himself that was so lavish and beautiful that the term “mausoleum” would subsequently be used for any stately tomb. Planned before his death in the city of Halicarnassus, a coastal town on the shores of what is now western Turkey, it was completed after his death in 353 BCE. Many writings from antiquity mention the Mausoleum’s beauty, and it was declared one of the seven wonders of the ancient world. Artemisia, widow to Mausolus, hired famous sculptors to work the stone and marble, and its sides were emblazoned with bas-reliefs of mythical creatures. Atop a pyramidal roof, supported by columns and solid stone, was a bronze chariot bearing depictions of Mausolus and Artemisia, together in death for eternity—or the early 15th Century, when the whole thing was toppled by earthquakes.");
            dataSource.insertWonder("Meenakshi Temple", "Medieval", "+3 Faith, Grants 2 Gurus, Gurus are 30% cheaper to purchase, Religious units adjacent to Gurus gain +5 Religious Strength in Theological Combat and +1 Movement.", "Must be built adjacent to a Holy Site district, and player must have founded a religion.", "Civil Service", "710 production","The Meenakshi Amman Temple dates back to the first century and is one of the oldest temples in India, still receiving thousands of visitors daily. Devoted to the goddess Meenakshi, a representation of love and fertility, this colorful complex spans 14 acres and is composed of tall walls, various shrines, 14 Gopurams (ornate gatehouse towers), and several Manapams (pillared halls). Fandom may earn an affiliate commission on sales made from links on this page. Brightly painted ceilings and stone carvings can be throughout the complex, but it is perhaps the thousands of vibrant stone statues lining the towers that have become most iconic. These small sculptures depict moments from Hindu stories – gods, demons, heroes, and animals. Every twelve years, these works are repainted and repaired. The Temple is host to private prayer and meditation, as well as monthly festivals throughout the year.");
            dataSource.insertWonder("Mont St. Michel", "Medieval", "+2 Faith, +2 Relic slots, All Apostles you create gain the Martyr ability in addition to a second ability you choose normally.", "Must be built on Floodplains or Marsh.", "Divine Right", "710 production","Perched on a rocky islet between Normandy and Brittany in the midst of sandbanks washed over by ocean tides, Mont St. Michel is a Gothic-style Benedictine abbey dedicated to the archangel Micheal built between the 11th and 16th centuries. Besides St. Aubert's skull, the Mont also was repository for bits of St. Petroc and St. Olaf and other holy relics. The place did have a practical purpose; its high walls, turrets and position made it of strategic worth … and many a French king stationed a small garrison (all that was needed) there. At low tide, it was readily accessible to pilgrims eager to give up a coin or two to be blessed; at high tide, the incoming sea would strand or drown any attacking force. The Mont would remain unconquered throughout the Hundred Years' War and beyond. Its position also made it ideal to incarcerate unrepentant traitors and other sinners; Louis XI turned the Mont into a prison, a role it served through the rest of the Ancien Régime. Now, it's still an abbey hosting a religious community, as well as a highly touristic visited place.");
            dataSource.insertWonder("Oracle", "Ancient", "+1 Culture, +1 Faith, Patronage of Great People costs 25% less Faith, Districts in this city provide +2 Great Person points of their type.", "Must be built on Hills.", "Mysticism", "290 production","Of all the places in ancient Greece where priestesses uttered prognostications, by far the most famous (and cryptic) was the Oracle at Delphi, a shrine to Apollo located on the slopes of Mount Parnassus. There a priestess known as the “Pythia” would – for suitable compensation – interpret dreams, commune with the gods while in a trance, and read the signs in the entrails of sacrificed animals (chickens for the cheap, or goats for those willing to pay more). The Oracle began operation as early as 1400 BC, and enjoyed a thriving business until Christianity arrived with the Romans. The greatest structure was the stately temple to Apollo (of course), and it stayed standing until pulled down on orders from Theodosius I in 390 AD. The site remained an active “pagan” center throughout the 4th Century, however, and the Pythian Games (a predecessor to the Olympics today) continued to at least 424 AD.");
            dataSource.insertWonder("Országház", "Industrial", "+4 Culture, +100% Diplomatic Favor per turn from starting a turn as a Suzerain of a city-state.", "Must be built on a River.", "Sanitation", "920 production","Orszaghaz translates to “House of the Country” but is better known as the Hungarian Parliament Building. This important building houses the members of Parliament, Hungarian Holy Crown, and the offices of the Prime Minister and staff. Fandom may earn an affiliate commission on sales made from links on this page. But aside from its significance to the government of Hungary, this building itself is an impressive display of Gothic Revival architecture. Overlooking the Danube River, the long wing spans 268 meters, and it is the tallest building in Budapest. Two identical halls for the Lower and Upper houses of Parliament stretch beyond a tall, central dome. Decorating the exterior façade are 90 stone sculptures that portray great moments of Hungarian history, as well as ornately carved stone. If that wasn't enough to excite visitors to this grand building, the precious stones and 88 lbs of gold used for decoration should do the trick.");
            dataSource.insertWonder("Oxford University", "Industrial", "+3 Great Scientist points per turn, +2 Great Works of Writing slots, +20% Science in city, and awards 2 randomly chosen free technologies when completed.", "Must be built on flat Grasslands or Plains adjacent to a Campus district with a University.", "Scientific Theory", "1240 production","The oldest university in the English-speaking world (and, thus, of Merry Ol’ England), instruction has been taking place at Oxford University since c. 1096 AD. It grew from a small institution when, in 1148, Henry II granted it a royal charter and then, in 1167, prohibited British students from attending the University of Paris. Although it was a Royalist center during the English Civil War, having survived that error the university has since taken little part in politics. In the mid-1800s the Oxford curriculum was greatly influenced by the reformed model of German higher education which came with the arrival of scholars such as Pusey, Jowett and Muller. The first women’s college (Lady Margaret Hall) at Oxford University was established in 1878. And in 1974, five previously all-male colleges there admitted women for the first time. Things haven’t been the same since.");
            dataSource.insertWonder("Panama Canal", "Industrial", "Upon completion 1 or 2 adjacent Canal districts are automatically constructed, The Canal wonder tile can now be crossed by naval units, +10 Gold.", "Must be built on a flat land tile where there are two adjacent tiles directly across the build tile from one another the meets the following criteria: one adjacent tile must be able to legally hold a Canal district connecting into the Panama Canal construction tile; the other must be either a city, a water tile, or be another tile that can hold a connecting Canal.", "Steam Power", "920 production","On August 15, 1914, just after the start of World War I, the Panama Canal officially opened. This direct water passage through Panama to link the Atlantic and Pacific oceans was first dreamed of in the 1500s, but it took several failed attempts and hundreds of years to see the project to fruition. Stretching for 50 miles across the Panama isthmus, the project was completed under supervision of the United States and remained under their control until 1999, when control passed to Panama. The canal itself is made up of man-made lakes separated by a system of locks. Using chambers in the locks locks, ships can be raised or lowered to match the water level at the next lake before continuing their journey through the canal. Today, about 14,000 ships cross through the Panama Canal each year, and each one pays a toll based on its type, size, and cargo.");
            dataSource.insertWonder("Petra", "Classical", "+2 Food and +2 Gold and +1 Production on all Desert tiles for this city(non-Floodplains).", "Must be built on Desert or Floodplains without Hills.", "Mathematics", "400 production","Situated between the Red Sea and the Dead Sea, Petra is a city cut from the red sandstone around Wadi Musa (now part of Jordan) by the Nabataeans – who obviously had a lot of free time – around 400 BC. Mentioned in Egyptian, Greek and Biblical sources, the city would develop into a major caravan center, a vital crossroads between Arabia, Egypt and Syria to the north. Surrounded by mountains riddled with gorges and canyon passages, it was defensible; but it was the ingenious and extensive system of cisterns and reservoirs in the middle of a desert that made it a trade center. At its peak, Petra was home to perhaps 20 thousand inhabitants, and served as the capital of the Nabataean kingdom. That is, until the Romans arrived and annexed it in 106 AD. Struck by a series of earthquakes, as well as Roman taxes, it was essentially abandoned two hundred years after – not to be “discovered” until 1812 by the Swiss explorer Johann Burckhardt.");
            dataSource.insertWonder("Potala Palace", "Renaissance", "+2 Culture, +3 Faith, +1 Diplomatic policy slot, +1 Diplomatic Victory Point when built.", "Must be built on a Hill adjacent to a Mountain.", "Astronomy", "1060 production","Since there wasn’t much level ground in Tibet, with its base set on the southern slope of the Red Hill, the Potala Palace – home to the Dalai Lama (until the fourteenth one fled an uprising in 1959) – sort of grew along the hillside. The palace is named after Mount Potalaka, abode of the eleven-headed bodhisattva Avalokiteśvara. Today, its crimson and white walls and golden roof “shine in glory” … for paying tourists. Lozang Gyatso, the fifth Dalai Lama, began construction of the “modern” palace above Lhasa c. 1645 AD, and moved in four years later. Since then more bits and pieces have been added to the sprawling edifice, notably the Potrang Marpo (“red palace”) and the holy stupa completed in 1694. However, it should be noted that the Potala Palace has only one bathroom, located on the right side of the White Palace Square … although it is said to be the most beautiful restroom on Earth, filled with sunlight and good thoughts.");
            dataSource.insertWonder("Pyramids", "Ancient", "+2 Culture, Grants a free Builder, All Builders can build one extra improvement.", "Must be built on Desert (including Floodplains) without Hills.", "Masonry", "220 production","Though pyramids were built from the beginning of the Old Kingdom to the close of the Ptolemaic dynasty, the really big heaps of stone along the Nile were piled up commencing in the late third dynasty and continuing through the sixth (roughly 500 years). The Great Pyramid of Giza that is virtually synonymous with the “glory”  of ancient Egypt went up around 2560 BC to serve as the tomb of Pharaoh Khufu (who is unremarkable for anything else save the length of his reign). It is considered one of the Seven Wonders of the Ancient World. Built by tens of thousands of workers, including skilled masons, and covered with “casing stones” (slabs of polished limestone), the Pyramids of Giza were a testament to Egypt’s power and the natives’ conviction of the afterlife – at least for the elite. To date, some 135 pyramids have been found in what was once the greatest empire in the world.");
            dataSource.insertWonder("Ruhr Valley", "Industrial", "+20 Production in this city, and +1 Production for each Mine and Quarry in this city.", "Must be built along a River adjacent to an Industrial Zone district with a Factory.", "Industrialization", "1240 production","Since the 1700s, the Ruhrpott (Ruhr Valley) has been dug up – the coal and iron mines there are some of the most productive in the world. Initially the ore was easily accessible by strip mining; after that was exhausted, the German miners dug deeper. By 1850, some 300 mines were in operation in and around the Ruhrpott. And, since it was troublesome to ship all this elsewhere, collieries, blast furnaces, rolling mills and the high chimneys of the Industrial Revolution shaped the skyline. Nor was coal and steel the only things pouring out of the Ruhr; by 1820 hundreds of water-powered mills were producing textiles, lumber and iron bars. Urban centers filled with wage slaves sprawled across the land … until today Bochum, Dortmund, Duisburg and Essen form one interconnected metropolis. With the recent decline of the coal and iron industries, the Ruhrpott has undergone a cultural transformation, and such edifices as the Zeche Zollverein coal mine complex and the Gasometer Oberhausen have been reborn as historical landmarks, even listed by UNESCO as World Heritage Sites!");
            dataSource.insertWonder("St. Basil's Cathedral", "Renaissance", "+3 Relic slots, +100% Tourism from this city, +1 Food, Production, and Culture from all Tundra tiles for this city.", "Must be built adjacent to a City Center", "Reformed Church", "920 production","The large, dramatically colored cathedral near Moscow’s Moskva River officially bore the name “Cathedral of the Intercession of the Virgin by the Moat,” but most people referred to it as “St. Basil’s.” Also, the shorter name fits better on maps. Ivan the Terrible commissioned its construction in 1555 to commemorate victories achieved during his reign. Despite Ivan’s namesake, the cathedral turned out to be anything but terrible. The cathedral is reminiscent of a Russian nesting doll, consisting of eight separate clustered churches rather than a single one. Though St. Basil’s was originally a drab white, it received a fresh coat of bold, patterned paint in 1860 that has defined it since.");
            dataSource.insertWonder("Statue of Liberty", "Industrial", "+4 Diplomatic Victory points when built, All your cities within 6 tiles are 100% loyal.", "Must be built on a Coast adjacent to land and a Harbor.", "Civil Engineering", "1240 production","Perhaps nothing is more iconic to America than the giant green woman standing in New York Harbor. Professor Edouard de Laboulaye and sculptor Frederic-Auguste Bartholdi didn’t hold back when creating the towering copper statue. It took twenty-one years for Laboulaye’s vision of Lady Liberty to come to life. Though ten years too late for America’s centennial, the people didn’t mind the delay—any present that arrives in 214 boxes must be a fantastic gift. Fandom may earn an affiliate commission on sales made from links on this page. Even before its final assembly in 1886, it earned the nickname “the New Colossus” thanks to poet Emma Lazarus. The statue quickly became a symbol of freedom and hope; her beacon acting as a lighthouse for the tired and poor, beckoning people to the shores of the United States with the promise of shelter and a new beginning");
            dataSource.insertWonder("Stonehenge", "Ancient", "+2 Faith, Grants a free Great Prophet, Great Prophets may found a religion on Stonehenge instead of a Holy Site.", "Must be built on flat land adjacent to Stone (Civ6) Stone.", "Astrology", "180 production","Whatever would motivate a bunch of Neolithic savages to build a circle out of fifty-ton slabs of rock – be it religious fervor, astrological curiosity, royal burial, or just for the fun of it – there’s no denying that Stonehenge is an impressive feat of engineering, given the tools they had to work with. Begun in Southern England some 5000 years ago, Stonehenge was concentric circles of stones surrounded by a moat (or “henge”). After the henge was in place, about a thousand years later an inner ring of “bluestones” were set in place, followed by an outer ring of larger, upright “sarsen” stones some 500 years after that. The 80 bluestones, coming in at about four tons each, were transported from a quarry over 240 miles away; the sarsen stones were cut and transported about 20 miles to the site. However done, for whatever purpose, Stonehenge remains a “wondrous” achievement even after a few millennia.");
            dataSource.insertWonder("Sydney Opera House", "Atomic", "+8 Culture, +5 Great Musician points per turn, +3 Great Works of Music slots.", "Must be built on Coast adjacent to a Harbor. Cannot be built on a Lake.", "Cultural Heritage", "1850 production","The construction of an enormous arts center for Sydney on Bennelong Point had been debated since the 1940s; in 1956 AD the government of New South Wales announced an open-ended competition for the design of something grand to show the world that the city really did have some taste. A Danish architect, Jørn Utzon won with his unique expressionist design, a series of precast concrete “shells,” covered with over a million white- or cream-colored tiles with interior glass curtain walls. So unique was the problematic design (Utzon had paid no heed to structural engineering) that it took sixteen years to build at a cost ten times more than estimated. But, once completed and officially dedicated by Queen Elizabeth II in October 1973, it has since become the iconic symbol of the one-time penal colony. From its 2,679-seat grand Concert Hall to the intimate 210-seat Utzon Room, the Opera House brings performances of all sorts down under.");
            dataSource.insertWonder("Taj Mahal", "Renaissance", "+1 Era Score from Historic Moments earned after the wonder is complete if that moment is usually worth 2 or more Era Score.", "Must be built next to a River.", "Humanism", "920 production","Mughal Emperor Shah Jahān had many wives, but Mumtāz Mahal (his third wife) was by far his favorite. After Mahal died in childbirth in 1631, Jahān immortalized his beloved with the grandest mausoleum he could imagine. The Taj Mahal’s construction required 20,000 laborers working for two decades. No mere tomb, the structure also housed a mosque and even a guesthouse—presumably for guests who preferred not to rest in a tomb. Fandom may earn an affiliate commission on sales made from links on this page. Jahān would not have long to appreciate the labors of 20,000 laborers. A violent succession struggle amongst his sons saw him placed under house arrest shortly after the Taj Mahal’s completion. Until his death in 1666, Jahān need only look out the window to observe his creation: the four tall minarets, the giant domed building seeming to fill the sky—all built with brick-in-lime mortar, red sandstone, and marble. The temple to Jahān’s love for Mahal still stands in India.");
            dataSource.insertWonder("Temple of Artemis", "Ancient", "+4 Food, +3 Housing, Each Camp, Pasture, and Plantation within 4 tiles provides +1 Amenity.", "Must be built next to a Camp.", "Archery", "180 production","Little remains of this once esteemed holy site. Dedicated to Artemis, the Greek Goddess of the Hunt, the temple suffered multiple devastations and underwent numerous rebuildings. It suffered damage from floods, raids, and arson caused by a man named Herostratus (who just wanted everyone to remember his name). Fandom may earn an affiliate commission on sales made from links on this page. In its best days, the temple was made of marble, gilded with gold and silver, and is said to have been longer than a football field. Philo of Byzantium, a Greek engineer and writer, declared that the splendor of temple put other contemporary wonders “in the shade. A final destruction at the dawn of the 5th Century, led by a Christian mob inspired by “gold-tongued” Saint John Chrysostom, ultimately spelled the end for the Temple of Artemis. In a way, the temple still lives on in present-day Turkey—its stone pillaged and incorporated into other buildings.");
            dataSource.insertWonder("Terracotta Army", "Classical", "+2 Great General points per turn, All current land units gain a promotion level, All Archaeologists from the owner may enter foreign lands without Open Borders.", "Must be built on flat Grassland or Plains adjacent to an Encampment district with a Barracks or Stable.", "Construction", "400 production","Since his efforts at immortality didn’t bear fruit, when it came time for Qin Shi Huang, first emperor of Qin, to be interred, he made sure that it was done with style as befitted his greatness. Never lacking in hubris, the emperor had ordered work to begin on his mausoleum in 246 BC, when he was but 13 years old and just ascended to the throne. According to the Chinese geographer Li Daoyuan, writing six centuries after, Mount Li was selected for the site because of its auspicious geology, with its southern face rich in jade and its northern slopes in gold. In the Records of the Grand Historian (by one Sima Qian), it is claimed some 700 thousand laborers would be employed in digging and outfitting the tomb and filling it with 8000 soldiers, 130 chariots with horses, and 150 mounted cavalry – all made from clay-based ceramic – and armed with functioning weapons. Arranged in military formation. Hence, the “Terracotta Army.” Undisturbed until 1974, when discovered by peasants attempting to dig a well. So much for hubris.");
            dataSource.insertWonder("University of Sankore", "Medieval", "+3 Science, +1 Faith, +2 Great Scientist points per turn, +2 Science for every Trade Route to this city, Domestic Trade Routes grant an additional +1 Faith to this city, Other Civilizations' Trade Routes to this city grant them +1 Science and +1 Gold.", "Must be built on a Desert or Desert Hill adjacent to a Campus with a University.", "Education", "710 production","Located within and around the pyramidal Sankore Mosque in Timbuktu, Sankore Madrasah was an ancient higher learning center that became especially prominent during the reign of Mansa Musa. The university operated differently than most modern universities today – instead of a central administration, the school was made up of independent schools with their own professors, and classes would take place outside in the courtyards or private homes. Though this may seem a bit more casual than what modern students experience, the University of Sankore was a renowned Islamic learning center. Curricula included Qur'anic studies of course, but also secular studies such as medicine, geography, physics, history, and art. The university offered four tiered degrees followed by graduation ceremonies during which students wore traditional turbans to represent their great accomplishments. In the 1590s, the Moroccan invasion of Mali pushed many scholars to leave – some were deported, while others fled – and much of the work of the university was destroyed.");
            dataSource.insertWonder("Venetian Arsenal", "Renaissance", "+2 Great Engineer points per turn, Receive a second naval unit each time you train a naval unit.", "Must be built on the Coast and adjacent to an Industrial Zone district.", "Mass Production", "920 production","The Arsenal of Venice, begun about 1104 AD, was eventually a sprawling complex of shipyards, armories, and weapons shops. Built to serve the needs of the Venetian Navy upon which the Republic relied for both its independence and its lucrative sea trade routes, it was termed “the most important example of a large production complex with a centralized structure of the pre-industrial” civilization. Different areas of the Arsenal produced a prefabricated ship part, armaments, rope, sails and everything needed to put together a warship in a single day if necessity demanded. A state-owned forest in the Montello hills provided the timber and tar. The Porto Magna (“great gate”) to the Arsenal was added c. 1460, from a design by the artist Jacopo Bellini, the first Classical Revival structure built in Venice; two stone lions, captured in Greece, were added to the entrance in 1687 to awe visitors. The Arsenal also, when not launching warships to beat down Venice’s challengers in the Mediterranean, produced most of the Venetian merchant ships bringing wealth back to the city-state … to build more ships.");
            insertWinCondition();
            wdrArrayList.setWonderArrayList();
        }

    }
    public void insertWinCondition() {

        dataSource.insertWinCondition("Alhambra", "1", "0", "0", "0", "0", "1");
        dataSource.insertWinCondition("Amundsen-Scott Research Station","1", "0", "1", "0", "0", "1");
        dataSource.insertWinCondition("Angkor Wat","0", "0", "0", "1", "0", "1");
        dataSource.insertWinCondition("Apadana","1", "1", "0", "0", "1", "1");
        dataSource.insertWinCondition("Big Ben","1", "1", "1", "1", "1", "1");
        dataSource.insertWinCondition("Bolshoi Theatre","0", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Broadway","0", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Casa de Contratación","1", "1", "1", "1", "1", "1");
        dataSource.insertWinCondition("Chichen Itza","1", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Colosseum","0", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Colossus","1", "1", "1", "1", "0", "1");
        dataSource.insertWinCondition("Cristo Redentor","0", "1", "0", "1", "0", "1");
        dataSource.insertWinCondition("Eiffel Tower","0", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Estádio do Maracanã", "0", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Forbidden City","0", "1", "0", "0", "1", "1");
        dataSource.insertWinCondition("Golden Gate Bridge","1", "1", "0", "0", "1", "1");
        dataSource.insertWinCondition("Great Bath","0", "0", "0", "1", "0", "1");
        dataSource.insertWinCondition("Great Library","0", "0", "1", "0", "0", "1");
        dataSource.insertWinCondition("Great Lighthouse","1", "0", "0", "0", "0", "1");
        dataSource.insertWinCondition("Great Zimbabwe","1", "1", "1", "1", "1", "1");
        dataSource.insertWinCondition("Hagia Sophia","0", "0", "0", "1", "0", "1");
        dataSource.insertWinCondition("Hanging Gardens","1", "1", "1", "1", "1", "1");
        dataSource.insertWinCondition("Hermitage","0", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Huey Toecalli","1", "1", "1", "1", "1", "1");
        dataSource.insertWinCondition("Jebel Barkal","1", "0", "0", "1", "0", "1");
        dataSource.insertWinCondition("Kilwa Kisiwani","0", "0", "0", "0", "1", "1");
        dataSource.insertWinCondition("Kotoku-in","0", "0", "0", "1", "0", "1");
        dataSource.insertWinCondition("Machu Picchu","1", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Mahabodhi Temple","0", "0", "0", "1", "0", "1");
        dataSource.insertWinCondition("Mausoleum at Halicarnassus","1", "1", "1", "1", "1", "1");
        dataSource.insertWinCondition("Meenakshi Temple","0", "0", "0", "1", "0", "1");
        dataSource.insertWinCondition("Mont St. Michel","0", "1", "0", "1", "0", "1");
        dataSource.insertWinCondition("Oracle","0", "1", "0", "1", "0", "1");
        dataSource.insertWinCondition("Országház","0", "1", "0", "0", "1", "1");
        dataSource.insertWinCondition("Oxford University","0", "1", "1", "0", "0", "1");
        dataSource.insertWinCondition("Panama Canal","1", "0", "0", "0", "0", "1");
        dataSource.insertWinCondition("Petra","1", "1", "1", "1", "1", "1");
        dataSource.insertWinCondition("Potala Palace","0", "1", "0", "1", "1", "1");
        dataSource.insertWinCondition("Pyramids","1", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Ruhr Valley","1", "0", "1", "0", "0", "1");
        dataSource.insertWinCondition("St. Basil's Cathedral","0", "1", "0", "1", "0", "1");
        dataSource.insertWinCondition("Statue of Liberty","0", "0", "0", "0", "1", "1");
        dataSource.insertWinCondition("Stonehenge","0", "0", "0", "1", "0", "1");
        dataSource.insertWinCondition("Sydney Opera House","0", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("Taj Mahal","1", "1", "1", "1", "1", "1");
        dataSource.insertWinCondition("Temple of Artemis","1", "1", "1", "0", "0", "1");
        dataSource.insertWinCondition("Terracotta Army","1", "1", "0", "0", "0", "1");
        dataSource.insertWinCondition("University of Sankore","0", "0", "1", "1", "1", "1");
        dataSource.insertWinCondition("Venetian Arsenal","1", "0", "0", "0", "0", "1");
    }
}
